In [3]:
import torch
from torch import nn
from torch.nn import functional as F 
from torchvision import datasets ,transforms

In [5]:
transform = transforms.Compose([transforms.ToTensor(),
                                transforms.Normalize((0.5,),(0.5)),
                                
])
transform
# To normalize the data

Compose(
    ToTensor()
    Normalize(mean=(0.5,), std=0.5)
)

In [6]:
trainset = datasets.MNIST("~/.pytorch/MNIST_data/",download =True,train=True,transform=transform)
trainset
#Downloading the dataset

Extracting /root/.pytorch/MNIST_data/MNIST/raw/train-images-idx3-ubyte.gz to /root/.pytorch/MNIST_data/MNIST/raw


Extracting /root/.pytorch/MNIST_data/MNIST/raw/train-labels-idx1-ubyte.gz to /root/.pytorch/MNIST_data/MNIST/raw


Extracting /root/.pytorch/MNIST_data/MNIST/raw/t10k-images-idx3-ubyte.gz to /root/.pytorch/MNIST_data/MNIST/raw


Extracting /root/.pytorch/MNIST_data/MNIST/raw/t10k-labels-idx1-ubyte.gz to /root/.pytorch/MNIST_data/MNIST/raw
Processing...
Done!


/usr/local/lib/python3.6/dist-packages/torchvision/datasets/mnist.py:469: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:141.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


Dataset MNIST
    Number of datapoints: 60000
    Root location: /root/.pytorch/MNIST_data/
    Split: Train
    StandardTransform
Transform: Compose(
               ToTensor()
               Normalize(mean=(0.5,), std=0.5)
           )

In [7]:
#Loading the dataset in torch
trainloader = torch.utils.data.DataLoader(dataset=trainset,batch_size=64,shuffle=True)
trainloader

In [8]:
#building the feedforward network
model = nn.Sequential(nn.Linear(in_features=784,out_features=128),
                      nn.ReLU(),
                      nn.Linear(in_features=128,out_features=64),
                      nn.ReLU(),
                      nn.Linear(in_features=64,out_features=10))
model

Sequential(
  (0): Linear(in_features=784, out_features=128, bias=True)
  (1): ReLU()
  (2): Linear(in_features=128, out_features=64, bias=True)
  (3): ReLU()
  (4): Linear(in_features=64, out_features=10, bias=True)
)

In [11]:
criterion = nn.CrossEntropyLoss()
criterion # defining loss function

CrossEntropyLoss()

In [12]:
images, labels = next(iter(trainloader)) # getting the data
print(images.shape,labels.shape)

torch.Size([64, 1, 28, 28]) torch.Size([64])


In [13]:
#flattening the images
images = images.view(images.shape[0],-1)
print(images.shape)


torch.Size([64, 784])


In [14]:
#forward pass and get our logits
logits = model(images)
print(logits.shape)

torch.Size([64, 10])


In [15]:
#calculating the loss
print(labels.shape)
loss = criterion(logits,labels)
print(loss)

torch.Size([64])
tensor(2.3197, grad_fn=<NllLossBackward>)


Example 2

In [16]:
print(images.shape,labels.shape)

torch.Size([64, 784]) torch.Size([64])


In [22]:
model = nn.Sequential(nn.Linear(in_features=784,out_features=128),
                       nn.ReLU(),
                       nn.Linear(128,64),
                       nn.ReLU(),
                       nn.Linear(64,10),
                       nn.LogSoftmax(dim=1)
                       
)
model

Sequential(
  (0): Linear(in_features=784, out_features=128, bias=True)
  (1): ReLU()
  (2): Linear(in_features=128, out_features=64, bias=True)
  (3): ReLU()
  (4): Linear(in_features=64, out_features=10, bias=True)
  (5): LogSoftmax(dim=1)
)

In [23]:
criterion = nn.NLLLoss()
# Already flatten
# feed forward pass
logps = model(images)
print(logps.shape)
loss= criterion(logps,labels)
print(loss)

torch.Size([64, 10])
tensor(2.2995, grad_fn=<NllLossBackward>)


AUTOGRADS


In [24]:
x = torch.randn(2,2,requires_grad=True)
x

tensor([[ 0.1011, -0.1975],
        [-0.6351, -0.5081]], requires_grad=True)

In [25]:
y = x**2
print(y)

tensor([[0.0102, 0.0390],
        [0.4034, 0.2582]], grad_fn=<PowBackward0>)


In [28]:
y.grad_fn # what is operation done before, grads will track the functions

In [29]:
z = y.mean()
z

tensor(0.1777, grad_fn=<MeanBackward0>)

In [30]:
#calculating the gradients for z with respect to the x
z.backward()
print(x.grad)
print(x/2)

tensor([[ 0.0506, -0.0988],
        [-0.3176, -0.2541]])
tensor([[ 0.0506, -0.0988],
        [-0.3176, -0.2541]], grad_fn=<DivBackward0>)


In [31]:
model

Sequential(
  (0): Linear(in_features=784, out_features=128, bias=True)
  (1): ReLU()
  (2): Linear(in_features=128, out_features=64, bias=True)
  (3): ReLU()
  (4): Linear(in_features=64, out_features=10, bias=True)
  (5): LogSoftmax(dim=1)
)

In [32]:
criterion

NLLLoss()

In [33]:
print(images.shape,labels.shape)

torch.Size([64, 784]) torch.Size([64])


In [35]:
logps = model(images)
print(logps.shape)

torch.Size([64, 10])


In [36]:
loss = criterion(logps,labels)
loss

tensor(2.2995, grad_fn=<NllLossBackward>)

In [42]:
print(model[0].weight.grad) # before backward pass 

None


In [43]:
model[0].weight

Parameter containing:
tensor([[ 0.0083, -0.0224, -0.0284,  ...,  0.0027,  0.0048,  0.0054],
        [-0.0078,  0.0012,  0.0231,  ..., -0.0275,  0.0007,  0.0317],
        [-0.0161, -0.0200,  0.0286,  ..., -0.0246,  0.0181, -0.0308],
        ...,
        [-0.0306, -0.0059,  0.0109,  ...,  0.0244,  0.0209, -0.0246],
        [ 0.0330, -0.0325,  0.0265,  ..., -0.0072,  0.0160, -0.0191],
        [ 0.0036, -0.0295,  0.0072,  ...,  0.0027, -0.0158,  0.0350]],
       requires_grad=True)

In [44]:
loss.backward()
print(model[0].weight.grad)# after backward pass

tensor([[ 6.0471e-04,  6.0471e-04,  6.0471e-04,  ...,  6.0471e-04,
          6.0471e-04,  6.0471e-04],
        [ 6.5891e-04,  6.5891e-04,  6.5891e-04,  ...,  6.5891e-04,
          6.5891e-04,  6.5891e-04],
        [-1.7529e-03, -1.7529e-03, -1.7529e-03,  ..., -1.7529e-03,
         -1.7529e-03, -1.7529e-03],
        ...,
        [ 2.1272e-03,  2.1272e-03,  2.1272e-03,  ...,  2.1272e-03,
          2.1272e-03,  2.1272e-03],
        [-3.2070e-05, -3.2070e-05, -3.2070e-05,  ..., -3.2070e-05,
         -3.2070e-05, -3.2070e-05],
        [-1.7257e-03, -1.7257e-03, -1.7257e-03,  ..., -1.7257e-03,
         -1.7257e-03, -1.7257e-03]])


In [45]:
model[0].weight

Parameter containing:
tensor([[ 0.0083, -0.0224, -0.0284,  ...,  0.0027,  0.0048,  0.0054],
        [-0.0078,  0.0012,  0.0231,  ..., -0.0275,  0.0007,  0.0317],
        [-0.0161, -0.0200,  0.0286,  ..., -0.0246,  0.0181, -0.0308],
        ...,
        [-0.0306, -0.0059,  0.0109,  ...,  0.0244,  0.0209, -0.0246],
        [ 0.0330, -0.0325,  0.0265,  ..., -0.0072,  0.0160, -0.0191],
        [ 0.0036, -0.0295,  0.0072,  ...,  0.0027, -0.0158,  0.0350]],
       requires_grad=True)

Optimizer 

In [47]:
from torch import optim

In [48]:
model.parameters()

<generator object Module.parameters at 0x7f6f90a4dca8>

In [56]:
optimizer = optim.SGD(params=model.parameters(),lr=0.9)
optimizer

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.9
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [57]:
#clear the gradients , dothis beacuse the gradients are accumalated-we no need to carry for every pass in training
optimizer.zero_grad()
#forward pass 
output = model(images)
#LOSS calculation
loss = criterion(output,labels)
#calculate the gradients
loss.backward()


In [58]:
model[0].weight #instial weights

Parameter containing:
tensor([[ 0.0083, -0.0224, -0.0284,  ...,  0.0027,  0.0048,  0.0054],
        [-0.0078,  0.0012,  0.0231,  ..., -0.0275,  0.0007,  0.0317],
        [-0.0161, -0.0200,  0.0286,  ..., -0.0246,  0.0181, -0.0308],
        ...,
        [-0.0306, -0.0059,  0.0109,  ...,  0.0243,  0.0208, -0.0247],
        [ 0.0330, -0.0325,  0.0265,  ..., -0.0072,  0.0160, -0.0191],
        [ 0.0036, -0.0295,  0.0072,  ...,  0.0028, -0.0158,  0.0351]],
       requires_grad=True)

In [59]:
#update the weights
optimizer.step()
model[0].weight # after updating the weights

Parameter containing:
tensor([[ 8.3984e-03, -2.2271e-02, -2.8266e-02,  ...,  2.8399e-03,
          4.8915e-03,  5.5524e-03],
        [-8.5557e-03,  4.9358e-04,  2.2365e-02,  ..., -2.8192e-02,
         -5.3708e-05,  3.0952e-02],
        [-1.4778e-02, -1.8647e-02,  2.9912e-02,  ..., -2.3290e-02,
          1.9446e-02, -2.9502e-02],
        ...,
        [-3.2802e-02, -8.0668e-03,  8.6972e-03,  ...,  2.2166e-02,
          1.8660e-02, -2.6816e-02],
        [ 3.3115e-02, -3.2395e-02,  2.6609e-02,  ..., -7.1155e-03,
          1.6078e-02, -1.9027e-02],
        [ 4.6778e-03, -2.8419e-02,  8.2684e-03,  ...,  3.8292e-03,
         -1.4705e-02,  3.6116e-02]], requires_grad=True)

In [60]:
epochs = 5
for e in range(epochs): # after completing all data in a dataset this loop will start again nothing but epoch
  running_loss = 0
  for images, labels in trainloader:
    images = images.view(images.shape[0],-1)
    optimizer.zero_grad()
    output = model(images)
    loss = criterion(output,labels)
    optimizer.step()
    running_loss = running_loss + loss.item()
  else:
    print(f"training loss : {running_loss/len(trainloader)}")


training loss : 2.3264539887401847
training loss : 2.3265459214700566
training loss : 2.326493129801394
training loss : 2.3265108790224804
training loss : 2.326446450849586


In [62]:
epochs = 1
for e in range(epochs): # after completing all data in a dataset this loop will start again nothing but epoch
  running_loss = 0
  count = 1
  for images, labels in trainloader:
    images = images.view(images.shape[0],-1)
    optimizer.zero_grad()
    output = model(images)
    loss = criterion(output,labels)
    optimizer.step()
    loss_each = loss.item()
    #running_loss = running_loss + loss_each
    print(round(loss_each,2),end = ',')
    count = count +1
    if count == 10:
      break
  # else:
  #   print(f"training loss : {running_loss/len(trainloader)}")


2.24,2.31,2.32,2.35,2.42,2.3,2.35,2.32,2.27,